### ISSUE TITLE
Add a merge instruction variant that retains the source account

### ISSUE THREAD

**Issue by t-nelson** [solana-program/stake-program#2]
#### Problem

the merge instruction today folds the source account's rent-exempt-reserve balance in to the destination account's undelegated lamports balance. to regain access to these lamports, the withdraw authority must be made available, which may not be ideal for some security or onchain program use cases, like stake pools. this creates a negative incentive for these use cases to minimize the number of stake accounts under management, as merge/split cycles effectively ratchet rent-exempt-reserve, harming capital efficiency

#### Solution

add a new merge instruction that retains the source account intact with full rent-exempt-reserve balance and a zero-lamport delegation

**Comment by 2501babe** [comment]
handled by https://github.com/solana-foundation/solana-improvement-documents/pull/148
