### ISSUE TITLE
Add a split variant that uses a mergeable account as the destination

### ISSUE THREAD

**Issue by joncinque** [solana-program/stake-program#3]
#### Problem

The "split" instruction on the stake program only works with blank accounts as the destination, which can limit its use. For example, if you have two stake accounts both delegated to the same validator, owned by the same authorities, etc, it's impossible shift any delegation amount from one to the other.

#### Proposed solution

Add a variant of the "split" instruction that accepts a mergeable account as the destination. This makes it possible to move any delegated amount between two accounts.

**Comment by 2501babe** [comment]
handled by https://github.com/solana-foundation/solana-improvement-documents/pull/148
