### ISSUE TITLE
Add a split variant that accepts an inactive stake

### ISSUE THREAD

**Issue by joncinque** [solana-program/stake-program#4]
#### Problem

The "split" instruction is limited to only new stake accounts as the destination. This requires some amount of rent-exempt SOL to be kept around if a client is doing a lot of splitting. Additionally, if someone only has stake authority, and they want to move active delegations around, they must provide the rent-exemption for the split destination.

#### Proposed solution

Going along with #3, also allow splits to go into inactive stake accounts. The main question: should we force the destination stake account to have the same permissions as the source account?

**Comment by 2501babe** [comment]
handled by https://github.com/solana-foundation/solana-improvement-documents/pull/148

**Comment by 2501babe** [comment]
handled by https://github.com/solana-foundation/solana-improvement-documents/pull/148
